//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AgenciaViajesEntities : DbContext
    {
        public AgenciaViajesEntities()
            : base("name=AgenciaViajesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AEROPUERTO> AEROPUERTO { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Pasajeros> Pasajeros { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<Vuelos> Vuelos { get; set; }
    
        public virtual int AgregarCiudad(string codigoCiudad, string nomCiudad, string pais)
        {
            var codigoCiudadParameter = codigoCiudad != null ?
                new ObjectParameter("codigoCiudad", codigoCiudad) :
                new ObjectParameter("codigoCiudad", typeof(string));
    
            var nomCiudadParameter = nomCiudad != null ?
                new ObjectParameter("nomCiudad", nomCiudad) :
                new ObjectParameter("nomCiudad", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AgregarCiudad", codigoCiudadParameter, nomCiudadParameter, paisParameter);
        }
    
        public virtual int AltaPasajero(Nullable<int> nroVenta, string numPasaporte, Nullable<int> nroAsiento)
        {
            var nroVentaParameter = nroVenta.HasValue ?
                new ObjectParameter("nroVenta", nroVenta) :
                new ObjectParameter("nroVenta", typeof(int));
    
            var numPasaporteParameter = numPasaporte != null ?
                new ObjectParameter("numPasaporte", numPasaporte) :
                new ObjectParameter("numPasaporte", typeof(string));
    
            var nroAsientoParameter = nroAsiento.HasValue ?
                new ObjectParameter("nroAsiento", nroAsiento) :
                new ObjectParameter("nroAsiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AltaPasajero", nroVentaParameter, numPasaporteParameter, nroAsientoParameter);
        }
    
        public virtual int AltaVentas(Nullable<int> monto, string usulog, string codigoVuelo, string numPasaporte)
        {
            var montoParameter = monto.HasValue ?
                new ObjectParameter("monto", monto) :
                new ObjectParameter("monto", typeof(int));
    
            var usulogParameter = usulog != null ?
                new ObjectParameter("usulog", usulog) :
                new ObjectParameter("usulog", typeof(string));
    
            var codigoVueloParameter = codigoVuelo != null ?
                new ObjectParameter("codigoVuelo", codigoVuelo) :
                new ObjectParameter("codigoVuelo", typeof(string));
    
            var numPasaporteParameter = numPasaporte != null ?
                new ObjectParameter("numPasaporte", numPasaporte) :
                new ObjectParameter("numPasaporte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AltaVentas", montoParameter, usulogParameter, codigoVueloParameter, numPasaporteParameter);
        }
    
        public virtual int AltaVuelo(string codigoVuelo, Nullable<System.DateTime> fechaPartida, Nullable<System.DateTime> fechaLlegada, Nullable<int> cantAsientos, Nullable<int> precioPasaje, string codigoAeropOrigen, string codigoAeropDestino)
        {
            var codigoVueloParameter = codigoVuelo != null ?
                new ObjectParameter("codigoVuelo", codigoVuelo) :
                new ObjectParameter("codigoVuelo", typeof(string));
    
            var fechaPartidaParameter = fechaPartida.HasValue ?
                new ObjectParameter("fechaPartida", fechaPartida) :
                new ObjectParameter("fechaPartida", typeof(System.DateTime));
    
            var fechaLlegadaParameter = fechaLlegada.HasValue ?
                new ObjectParameter("fechaLlegada", fechaLlegada) :
                new ObjectParameter("fechaLlegada", typeof(System.DateTime));
    
            var cantAsientosParameter = cantAsientos.HasValue ?
                new ObjectParameter("cantAsientos", cantAsientos) :
                new ObjectParameter("cantAsientos", typeof(int));
    
            var precioPasajeParameter = precioPasaje.HasValue ?
                new ObjectParameter("precioPasaje", precioPasaje) :
                new ObjectParameter("precioPasaje", typeof(int));
    
            var codigoAeropOrigenParameter = codigoAeropOrigen != null ?
                new ObjectParameter("codigoAeropOrigen", codigoAeropOrigen) :
                new ObjectParameter("codigoAeropOrigen", typeof(string));
    
            var codigoAeropDestinoParameter = codigoAeropDestino != null ?
                new ObjectParameter("codigoAeropDestino", codigoAeropDestino) :
                new ObjectParameter("codigoAeropDestino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AltaVuelo", codigoVueloParameter, fechaPartidaParameter, fechaLlegadaParameter, cantAsientosParameter, precioPasajeParameter, codigoAeropOrigenParameter, codigoAeropDestinoParameter);
        }
    
        public virtual ObjectResult<BuscarCiudad_Result> BuscarCiudad(string codigoCiudad)
        {
            var codigoCiudadParameter = codigoCiudad != null ?
                new ObjectParameter("codigoCiudad", codigoCiudad) :
                new ObjectParameter("codigoCiudad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarCiudad_Result>("BuscarCiudad", codigoCiudadParameter);
        }
    
        public virtual ObjectResult<BuscarCiudadActiva_Result> BuscarCiudadActiva(string codigoCiudad)
        {
            var codigoCiudadParameter = codigoCiudad != null ?
                new ObjectParameter("codigoCiudad", codigoCiudad) :
                new ObjectParameter("codigoCiudad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarCiudadActiva_Result>("BuscarCiudadActiva", codigoCiudadParameter);
        }
    
        public virtual ObjectResult<BuscarEmpleado_Result> BuscarEmpleado(string nomUs)
        {
            var nomUsParameter = nomUs != null ?
                new ObjectParameter("nomUs", nomUs) :
                new ObjectParameter("nomUs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarEmpleado_Result>("BuscarEmpleado", nomUsParameter);
        }
    
        public virtual int CreoUsuarioComun(string usuLog, string usuPass)
        {
            var usuLogParameter = usuLog != null ?
                new ObjectParameter("usuLog", usuLog) :
                new ObjectParameter("usuLog", typeof(string));
    
            var usuPassParameter = usuPass != null ?
                new ObjectParameter("usuPass", usuPass) :
                new ObjectParameter("usuPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreoUsuarioComun", usuLogParameter, usuPassParameter);
        }
    
        public virtual int EliminarCiudad(string codigoCiudad)
        {
            var codigoCiudadParameter = codigoCiudad != null ?
                new ObjectParameter("codigoCiudad", codigoCiudad) :
                new ObjectParameter("codigoCiudad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarCiudad", codigoCiudadParameter);
        }
    
        public virtual ObjectResult<ListadoVuelos_Result> ListadoVuelos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListadoVuelos_Result>("ListadoVuelos");
        }
    
        public virtual ObjectResult<listarAeropuerto_Result> listarAeropuerto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarAeropuerto_Result>("listarAeropuerto");
        }
    
        public virtual ObjectResult<listarClientes_Result> listarClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarClientes_Result>("listarClientes");
        }
    
        public virtual ObjectResult<ListarPasajeros_Result> ListarPasajeros(Nullable<int> nroVenta)
        {
            var nroVentaParameter = nroVenta.HasValue ?
                new ObjectParameter("nroVenta", nroVenta) :
                new ObjectParameter("nroVenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPasajeros_Result>("ListarPasajeros", nroVentaParameter);
        }
    
        public virtual ObjectResult<ListarVentasCliente_Result> ListarVentasCliente(string numPasporte)
        {
            var numPasporteParameter = numPasporte != null ?
                new ObjectParameter("numPasporte", numPasporte) :
                new ObjectParameter("numPasporte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarVentasCliente_Result>("ListarVentasCliente", numPasporteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LogueoEmpleado(string usuLog, string usuPass)
        {
            var usuLogParameter = usuLog != null ?
                new ObjectParameter("usuLog", usuLog) :
                new ObjectParameter("usuLog", typeof(string));
    
            var usuPassParameter = usuPass != null ?
                new ObjectParameter("usuPass", usuPass) :
                new ObjectParameter("usuPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LogueoEmpleado", usuLogParameter, usuPassParameter);
        }
    
        public virtual int ModificarCiudad(string codigoCiudad, string nomCiudad, string pais)
        {
            var codigoCiudadParameter = codigoCiudad != null ?
                new ObjectParameter("codigoCiudad", codigoCiudad) :
                new ObjectParameter("codigoCiudad", typeof(string));
    
            var nomCiudadParameter = nomCiudad != null ?
                new ObjectParameter("nomCiudad", nomCiudad) :
                new ObjectParameter("nomCiudad", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarCiudad", codigoCiudadParameter, nomCiudadParameter, paisParameter);
        }
    
        public virtual int sp_AgregarAeropuerto(string codigoCiudad, string codigoAP, Nullable<int> impLlegada, Nullable<int> impPartida, string nombreAP, string direccion)
        {
            var codigoCiudadParameter = codigoCiudad != null ?
                new ObjectParameter("CodigoCiudad", codigoCiudad) :
                new ObjectParameter("CodigoCiudad", typeof(string));
    
            var codigoAPParameter = codigoAP != null ?
                new ObjectParameter("CodigoAP", codigoAP) :
                new ObjectParameter("CodigoAP", typeof(string));
    
            var impLlegadaParameter = impLlegada.HasValue ?
                new ObjectParameter("ImpLlegada", impLlegada) :
                new ObjectParameter("ImpLlegada", typeof(int));
    
            var impPartidaParameter = impPartida.HasValue ?
                new ObjectParameter("ImpPartida", impPartida) :
                new ObjectParameter("ImpPartida", typeof(int));
    
            var nombreAPParameter = nombreAP != null ?
                new ObjectParameter("NombreAP", nombreAP) :
                new ObjectParameter("NombreAP", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AgregarAeropuerto", codigoCiudadParameter, codigoAPParameter, impLlegadaParameter, impPartidaParameter, nombreAPParameter, direccionParameter);
        }
    
        public virtual int sp_AgregarCliente(string numPasaporte, string nombreCliente, string clientePass, Nullable<int> numTarjeta)
        {
            var numPasaporteParameter = numPasaporte != null ?
                new ObjectParameter("NumPasaporte", numPasaporte) :
                new ObjectParameter("NumPasaporte", typeof(string));
    
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("NombreCliente", nombreCliente) :
                new ObjectParameter("NombreCliente", typeof(string));
    
            var clientePassParameter = clientePass != null ?
                new ObjectParameter("ClientePass", clientePass) :
                new ObjectParameter("ClientePass", typeof(string));
    
            var numTarjetaParameter = numTarjeta.HasValue ?
                new ObjectParameter("NumTarjeta", numTarjeta) :
                new ObjectParameter("NumTarjeta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AgregarCliente", numPasaporteParameter, nombreClienteParameter, clientePassParameter, numTarjetaParameter);
        }
    
        public virtual ObjectResult<sp_BuscarAeropuertoActivo_Result> sp_BuscarAeropuertoActivo(string codigoAP)
        {
            var codigoAPParameter = codigoAP != null ?
                new ObjectParameter("CodigoAP", codigoAP) :
                new ObjectParameter("CodigoAP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuscarAeropuertoActivo_Result>("sp_BuscarAeropuertoActivo", codigoAPParameter);
        }
    
        public virtual ObjectResult<sp_BuscarAeropuertoTodos_Result> sp_BuscarAeropuertoTodos(string codigoAP)
        {
            var codigoAPParameter = codigoAP != null ?
                new ObjectParameter("CodigoAP", codigoAP) :
                new ObjectParameter("CodigoAP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuscarAeropuertoTodos_Result>("sp_BuscarAeropuertoTodos", codigoAPParameter);
        }
    
        public virtual ObjectResult<sp_BuscarClienteActivo_Result> sp_BuscarClienteActivo(string numPasaporte)
        {
            var numPasaporteParameter = numPasaporte != null ?
                new ObjectParameter("NumPasaporte", numPasaporte) :
                new ObjectParameter("NumPasaporte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuscarClienteActivo_Result>("sp_BuscarClienteActivo", numPasaporteParameter);
        }
    
        public virtual ObjectResult<sp_BuscarClienteTodos_Result> sp_BuscarClienteTodos(string numPasaporte)
        {
            var numPasaporteParameter = numPasaporte != null ?
                new ObjectParameter("NumPasaporte", numPasaporte) :
                new ObjectParameter("NumPasaporte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuscarClienteTodos_Result>("sp_BuscarClienteTodos", numPasaporteParameter);
        }
    
        public virtual int sp_EliminarAeropuerto(string codigoAP)
        {
            var codigoAPParameter = codigoAP != null ?
                new ObjectParameter("CodigoAP", codigoAP) :
                new ObjectParameter("CodigoAP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarAeropuerto", codigoAPParameter);
        }
    
        public virtual int sp_EliminarCliente(string numPasaporte)
        {
            var numPasaporteParameter = numPasaporte != null ?
                new ObjectParameter("NumPasaporte", numPasaporte) :
                new ObjectParameter("NumPasaporte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarCliente", numPasaporteParameter);
        }
    
        public virtual int sp_ModificarAeropuerto(string codigoCiudad, string codigoAP, Nullable<int> impLlegada, Nullable<int> impPartida, string nombreAP, string direccion)
        {
            var codigoCiudadParameter = codigoCiudad != null ?
                new ObjectParameter("CodigoCiudad", codigoCiudad) :
                new ObjectParameter("CodigoCiudad", typeof(string));
    
            var codigoAPParameter = codigoAP != null ?
                new ObjectParameter("CodigoAP", codigoAP) :
                new ObjectParameter("CodigoAP", typeof(string));
    
            var impLlegadaParameter = impLlegada.HasValue ?
                new ObjectParameter("ImpLlegada", impLlegada) :
                new ObjectParameter("ImpLlegada", typeof(int));
    
            var impPartidaParameter = impPartida.HasValue ?
                new ObjectParameter("ImpPartida", impPartida) :
                new ObjectParameter("ImpPartida", typeof(int));
    
            var nombreAPParameter = nombreAP != null ?
                new ObjectParameter("NombreAP", nombreAP) :
                new ObjectParameter("NombreAP", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarAeropuerto", codigoCiudadParameter, codigoAPParameter, impLlegadaParameter, impPartidaParameter, nombreAPParameter, direccionParameter);
        }
    
        public virtual int sp_ModificarCliente(string numPasaporte, string nombreCliente, string clientePass, Nullable<int> numTarjeta)
        {
            var numPasaporteParameter = numPasaporte != null ?
                new ObjectParameter("NumPasaporte", numPasaporte) :
                new ObjectParameter("NumPasaporte", typeof(string));
    
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("NombreCliente", nombreCliente) :
                new ObjectParameter("NombreCliente", typeof(string));
    
            var clientePassParameter = clientePass != null ?
                new ObjectParameter("ClientePass", clientePass) :
                new ObjectParameter("ClientePass", typeof(string));
    
            var numTarjetaParameter = numTarjeta.HasValue ?
                new ObjectParameter("NumTarjeta", numTarjeta) :
                new ObjectParameter("NumTarjeta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarCliente", numPasaporteParameter, nombreClienteParameter, clientePassParameter, numTarjetaParameter);
        }
    }
}
